# Generated by Django 5.2 on 2025-04-16 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cancer', '0002_alter_lungcancer_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lungcancer',
            name='alcohol_consumption',
            field=models.IntegerField(blank=True, choices=[(0, 'Não'), (1, 'Sim')], null=True),
        ),
        migrations.AlterField(
            model_name='lungcancer',
            name='breathing_issue',
            field=models.IntegerField(blank=True, choices=[(0, 'Não'), (1, 'Sim')], null=True),
        ),
        migrations.AlterField(
            model_name='lungcancer',
            name='chest_tightness',
            field=models.IntegerField(blank=True, choices=[(0, 'Não'), (1, 'Sim')], null=True),
        ),
        migrations.AlterField(
            model_name='lungcancer',
            name='energy_level',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lungcancer',
            name='exposure_to_pollution',
            field=models.IntegerField(blank=True, choices=[(0, 'Não'), (1, 'Sim')], null=True),
        ),
        migrations.AlterField(
            model_name='lungcancer',
            name='family_history',
            field=models.IntegerField(blank=True, choices=[(0, 'Não'), (1, 'Sim')], null=True),
        ),
        migrations.AlterField(
            model_name='lungcancer',
            name='finger_discoloration',
            field=models.IntegerField(blank=True, choices=[(0, 'Não'), (1, 'Sim')], null=True),
        ),
        migrations.AlterField(
            model_name='lungcancer',
            name='gender',
            field=models.IntegerField(blank=True, choices=[(0, 'Feminino'), (1, 'Masculino')], null=True),
        ),
        migrations.AlterField(
            model_name='lungcancer',
            name='immune_weakness',
            field=models.IntegerField(blank=True, choices=[(0, 'Não'), (1, 'Sim')], null=True),
        ),
        migrations.AlterField(
            model_name='lungcancer',
            name='long_term_illness',
            field=models.IntegerField(blank=True, choices=[(0, 'Não'), (1, 'Sim')], null=True),
        ),
        migrations.AlterField(
            model_name='lungcancer',
            name='mental_stress',
            field=models.IntegerField(blank=True, choices=[(0, 'Não'), (1, 'Sim')], null=True),
        ),
        migrations.AlterField(
            model_name='lungcancer',
            name='oxygen_saturation',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lungcancer',
            name='smoking',
            field=models.IntegerField(blank=True, choices=[(0, 'Não'), (1, 'Sim')], null=True),
        ),
        migrations.AlterField(
            model_name='lungcancer',
            name='smoking_family_history',
            field=models.IntegerField(blank=True, choices=[(0, 'Não'), (1, 'Sim')], null=True),
        ),
        migrations.AlterField(
            model_name='lungcancer',
            name='stress_imune',
            field=models.IntegerField(blank=True, choices=[(0, 'Não'), (1, 'Sim')], null=True),
        ),
        migrations.AlterField(
            model_name='lungcancer',
            name='throat_discomfort',
            field=models.IntegerField(blank=True, choices=[(0, 'Não'), (1, 'Sim')], null=True),
        ),
    ]
