# Generated by Django 5.2 on 2025-04-17 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_cancer', '0003_alter_lungcancer_alcohol_consumption_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lungcancer',
            old_name='stress_imune',
            new_name='stress_immune',
        ),
    ]
