# Generated by Django 5.2 on 2025-04-17 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cancer', '0004_rename_stress_imune_lungcancer_stress_immune'),
    ]

    operations = [
        migrations.AddField(
            model_name='lungcancer',
            name='resultado',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
